In [8]:
import numpy as np
import sys, os
from utils import default_paths
import pandas as pd

In [19]:
fn2load = os.path.join('/user_data/mmhender/nsd/labels/S1_within_prf_grid5_backup', \
                       'S1_cocolabs_binary_prf999.csv')
counts_old = pd.read_csv(fn2load, index_col=0)
sums = np.array(np.sum(counts_old))[12:92]
sums

array([5002.,  243.,  859.,  258.,  273.,  315.,  321.,  452.,  271.,
        313.,  127.,  143.,   52.,  423.,  283.,  366.,  374.,  231.,
        128.,  186.,  207.,  111.,  171.,  266.,  384.,  296.,  469.,
        306.,  173.,  178.,  322.,  147.,  332.,  188.,  186.,  219.,
        260.,  353.,  299.,  617.,  187.,  670.,  230.,  296.,  278.,
        570.,  202.,  126.,  169.,  120.,  162.,  131.,   93.,  258.,
        139.,  206.,  944.,  288.,  342.,  317.,  882.,  293.,  306.,
        236.,  130.,  191.,  142.,  338.,  136.,  250.,   16.,  415.,
        177.,  406.,  393.,  266.,   71.,  151.,   20.,   83.])

In [20]:
new_sums = out['things_cat_counts'][0,999,:]
new_sums.astype(int)

array([2164,   41,  109,  148,  166,  198,  244,  150,   79,   15,   36,
         57,   17,  114,   64,  247,  183,  122,   43,   87,  163,   82,
        109,  159,   12,   74,   21,   15,   75,   11,    3,    6,    1,
         20,    1,    6,   13,   38,    6,   33,   10,   52,    1,    3,
          1,  150,   72,   26,   98,   23,   46,   13,   46,  177,   51,
         97,  123,  156,   60,  267,  560,  105,   93,   99,    5,    9,
         39,   32,   31,   86,    4,   49,   96,   46,   29,   45,   12,
         87,    2,    6])

In [21]:
sums>new_sums

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [30]:
fn2load = os.path.join('/user_data/mmhender/nsd/labels/S1_within_prf_grid5_backup', \
                       'S1_cocolabs_stuff_binary_prf0.csv')
counts_old = pd.read_csv(fn2load, index_col=0)
sums = np.array(np.sum(counts_old))[16:108]
sums.astype(int)

array([  38,   13,   33,   26,  469,   99,  105,   58,   29,   23,   16,
          2,   11,   87,  221,   64,   12,   49,   31,  135,   73,  150,
          7,   30,   14,   38,   42,   37,   42,   82,   28,  137,  414,
         21,   63,   51,   70,   18,   21,    3,  159,   56,    4,   96,
          3,    9,   26,   52,  144,    6,   78,   54,   13,  169,   15,
         17,   51,  154,   33,   15,    3,   14,   85,  328,   46,  483,
         44,  239,   10,   12,   26,   22,   37,   89,   10,   66,   12,
        654,   34,   56,  462,  237,   28,   11,  165,   74,   54,    4,
         16,  103,   35, 6843])

In [31]:
new_sums = out['stuff_cat_counts'][0,0,:]
new_sums.astype(int)

array([  29,    8,   30,   23,  425,   79,   87,   50,   26,   18,   13,
          1,    6,   56,  195,   53,    7,   44,   28,  111,   64,  122,
          4,   24,   14,   30,   35,   33,   35,   77,   21,   96,  343,
         15,   51,   45,   57,   13,   17,    3,  126,   53,    4,   86,
          3,    6,   22,   43,  123,    3,   66,   40,    9,  158,    9,
         13,   40,  122,   29,   12,    3,   12,   71,  303,   39,  436,
         37,  214,    9,    9,   24,   17,   32,   72,    6,   52,    7,
        560,   27,   48,  403,  205,   22,    9,  153,   63,   51,    2,
         13,   89,   27, 6473])

In [32]:
sums>new_sums

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [2]:
labels_folder = os.path.join(default_paths.stim_labels_root)
which_prf_grid=5
fn2save = os.path.join(default_paths.stim_labels_root, \
                       'Coco_label_counts_all_prf_grid%d.npy'%(which_prf_grid))      
out = np.load(fn2save, allow_pickle=True).item()
out.keys()

dict_keys(['things_supcat_counts', 'things_cat_counts', 'stuff_supcat_counts', 'stuff_cat_counts', 'things_supcat_counts_trntrials', 'things_cat_counts_trntrials', 'stuff_supcat_counts_trntrials', 'stuff_cat_counts_trntrials', 'things_supcat_counts_valtrials', 'things_cat_counts_valtrials', 'stuff_supcat_counts_valtrials', 'stuff_cat_counts_valtrials'])

In [2]:
labels_folder = os.path.join(default_paths.stim_labels_root)
which_prf_grid=5
fn2save = os.path.join(default_paths.stim_labels_root, \
                       'Coco_label_counts_all_prf_grid%d.npy'%(which_prf_grid))      
out = np.load(fn2save, allow_pickle=True).item()
out.keys()

dict_keys(['things_supcat_counts', 'things_cat_counts', 'stuff_supcat_counts', 'stuff_cat_counts', 'things_supcat_counts_trntrials', 'things_cat_counts_trntrials', 'stuff_supcat_counts_trntrials', 'stuff_cat_counts_trntrials', 'things_supcat_counts_valtrials', 'things_cat_counts_valtrials', 'stuff_supcat_counts_valtrials', 'stuff_cat_counts_valtrials'])

In [4]:
out['things_cat_counts'].shape

(8, 1456, 80)

In [7]:
out['things_cat_counts'][:,0,:].astype(int)

array([[2173,   35,   80,  119,  177,  187,  236,  141,   95,   13,   47,
          44,   13,   72,   95,  230,  194,  129,   68,  106,  155,   88,
         125,  145,   25,   75,   35,   38,   60,   17,   11,    5,    3,
          35,    6,   14,   19,   59,   16,   40,   18,   57,    4,   10,
           7,  141,   63,   35,   80,   23,   48,   24,   44,  156,   63,
          82,  105,   60,   51,  123,  335,   80,   68,   68,    1,   14,
          27,   37,   25,   65,    1,   44,   64,   37,   49,   56,   17,
          76,    1,    8],
       [2103,   42,   83,  111,  197,  194,  259,  140,   86,   21,   42,
          33,   18,   81,   91,  215,  159,  127,   72,  121,  180,   87,
         135,  145,   25,   61,   31,   30,   57,   10,    5,    8,    8,
          20,    8,   17,   25,   52,   21,   53,   24,   59,    3,    7,
           9,  128,   66,   33,   89,   36,   51,   25,   33,  166,   49,
          90,   94,   51,   59,  127,  348,   69,   61,   78,    3,   13,
          2