In [1]:
import h5py
import time
import numpy as np

In [19]:
import sys
sys.path.append('/user_data/mmhender/imStat/code')
from utils import default_paths, torch_utils
alexnet_feat_path = default_paths.alexnet_feat_path
from feature_extraction import extract_alexnet_features
alexnet_layer_names  = extract_alexnet_features.alexnet_layer_names
n_features_each_layer = extract_alexnet_features.n_features_each_layer
n_features_each_conv_layer = np.array(n_features_each_layer)[[0,3,6,8,10]]


In [32]:
layer_name = 'Conv5_ReLU'
layer_ind = np.where([layer_name==a for a in alexnet_layer_names])[0][0]
n_features = n_features_each_layer[layer_ind]
n_features

256

In [23]:
n_features_each_conv_layer

array([ 64, 192, 384, 256, 256])

In [33]:
thing = np.load('/user_data/mmhender/features/alexnet/PCA/S1_Conv5_ReLU_reflect_PCA_grid5.npy', allow_pickle=True).item()
len(thing)

4

In [37]:
thing['ev'][1]

array([10.65921018,  9.12704504,  6.82578433,  5.86768018,  4.10458271,
        3.77086435,  2.94552876,  2.77036935,  2.54095377,  2.25131669,
        2.15204078,  2.09023986,  1.88605626,  1.78459746,  1.60203153,
        1.56450253,  1.40537405,  1.32529805,  1.21248032,  1.1808592 ,
        1.16631347,  1.02679477,  0.94018071,  0.92075687,  0.91498053,
        0.89659724,  0.84008568,  0.78308307,  0.77586108,  0.74835052,
        0.72796603,  0.70791987,  0.67316675,  0.66389788,  0.63665009,
        0.61408536,  0.58307404,  0.56916286,  0.54287948,  0.53851429,
        0.53220415,  0.50014204,  0.49626051,  0.47717274,  0.46665622,
        0.45328805,  0.43532197,  0.43112208,  0.41918914,  0.40554264,
        0.40147422,  0.38750104,  0.38306851,  0.37550485,  0.36649125,
        0.3524414 ,  0.34992323,  0.34790978,  0.34380652,  0.33198522,
        0.33098749,  0.32505638,  0.31454304,  0.31208772,  0.30121908,
        0.29515563,  0.29130454,  0.28747054,  0.28041961,  0.27

In [13]:
thing = np.load('/user_data/mmhender/features/sketch_tokens/PCA/S1_PCA_grid5.npy', allow_pickle=True).item()
len(thing)

4

In [14]:
len(thing['scores'])

1456

In [12]:
fn = '/user_data/mmhender/features/alexnet/S1_Conv3_ReLU_reflect_features_each_prf_grid5.h5py'
with h5py.File(fn,'r') as data_set:
    dsize = data_set['/features'].shape
print(dsize)

(10000, 384, 1456)


In [18]:
fn = '/user_data/mmhender/features/pyramid_texture/S1_features_each_prf_4ori_4sf_grid3.h5py'
# fn = '/user_data/mmhender/features/sketch_tokens/S1_features_each_prf_grid4.h5py'
t = time.time()
with h5py.File(fn, 'r') as data_set:
    print(data_set['/features'].shape)
    values = np.copy(data_set['/features'][:,:,900])
    
    data_set.close() 
elapsed = time.time() - t
print('Took %.5f seconds to load file'%elapsed)

values

(10000, 641, 1114)
Took 89.05967 seconds to load file


array([[ 4.52046663e-01,  8.41336176e-02,  1.08330309e-01, ...,
        -3.33649991e-03, -2.58855941e-03,  1.36148639e-03],
       [ 3.89485002e-01,  7.25870132e-02,  3.76383066e-01, ...,
        -1.61202811e-03, -1.41469855e-03,  5.11511171e-05],
       [ 6.30354822e-01,  1.81474369e-02, -1.31636858e+00, ...,
         2.13078863e-04,  8.57799139e-04,  1.28161605e-03],
       ...,
       [ 2.04624474e-01,  3.10997497e-02,  2.27002358e+00, ...,
         1.56933675e-04,  2.54149054e-04, -6.39250575e-05],
       [ 5.46117723e-01,  7.27616698e-02, -7.43180513e-01, ...,
        -6.03583816e-04,  5.44253213e-04,  2.51140073e-03],
       [ 2.91480720e-01,  3.64610516e-02,  8.07258010e-01, ...,
        -4.48623847e-04, -5.60720764e-06,  1.02754519e-03]])

In [11]:
import torch
thing = torch.load('/user_data/mmhender/imStat/model_fits/S01/sketch_tokens/Nov-04-2021_0115_51/all_fit_params')
                   

In [8]:
thing['which_prf_grid']

3

In [9]:
thing = torch.load('/user_data/mmhender/imStat/model_fits/S01/sketch_tokens/Nov-03-2021_1939_00/all_fit_params')


In [10]:
thing['which_prf_grid']

3

In [13]:
thing['models'].shape

(1114, 3)